"""The Aurora Whisper integration.

Sets up a Speech-to-Text entity backed by an OpenAI-compatible Whisper
transcription endpoint (e.g. https://api.staik.se/v1, KB-Whisper / whisper-1).

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from dataclasses import dataclass

from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant
from homeassistant.helpers.aiohttp_client import async_get_clientsession

from .api import AuroraWhisperClient
from .const import (
    CONF_API_KEY,
    CONF_BASE_URL,
    CONF_TIMEOUT,
    DEFAULT_TIMEOUT,
    PLATFORMS,
)


@dataclass
class AuroraWhisperRuntimeData:
    """Runtime objects stored on the config entry."""

    client: AuroraWhisperClient


type AuroraWhisperConfigEntry = ConfigEntry[AuroraWhisperRuntimeData]


async def async_setup_entry(
    hass: HomeAssistant, entry: AuroraWhisperConfigEntry
) -> bool:
    """Set up Aurora Whisper from a config entry."""
    config = {**entry.data, **entry.options}

    session = async_get_clientsession(hass)
    client = AuroraWhisperClient(
        session=session,
        base_url=config[CONF_BASE_URL],
        api_key=config.get(CONF_API_KEY, ""),
        timeout=config.get(CONF_TIMEOUT, DEFAULT_TIMEOUT),
    )

    entry.runtime_data = AuroraWhisperRuntimeData(client=client)

    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
    entry.async_on_unload(entry.add_update_listener(_async_reload_entry))
    return True


async def async_unload_entry(
    hass: HomeAssistant, entry: AuroraWhisperConfigEntry
) -> bool:
    """Unload a config entry."""
    return await hass.config_entries.async_unload_platforms(entry, PLATFORMS)


async def _async_reload_entry(
    hass: HomeAssistant, entry: AuroraWhisperConfigEntry
) -> None:
    """Reload the entry when its options change."""
    await hass.config_entries.async_reload(entry.entry_id)
