"""Async client for an OpenAI-compatible Whisper transcription API.

Talks to ``POST {base_url}/audio/transcriptions`` (multipart/form-data) and an
optional ``GET {base_url}/models`` for a best-effort connectivity/auth check.
All I/O uses the shared Home Assistant aiohttp session — never the blocking
``openai`` SDK or ``requests``.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

import logging

import aiohttp

from homeassistant.exceptions import HomeAssistantError

from .const import ENDPOINT_MODELS, ENDPOINT_TRANSCRIPTIONS

_LOGGER = logging.getLogger(__name__)


class AuroraWhisperError(HomeAssistantError):
    """Raised when the Whisper API cannot be reached or returns an error."""


class AuroraWhisperAuthError(AuroraWhisperError):
    """Raised when the API rejects the credentials (HTTP 401/403)."""


class AuroraWhisperClient:
    """Minimal async client for an OpenAI-compatible Whisper endpoint."""

    def __init__(
        self,
        session: aiohttp.ClientSession,
        base_url: str,
        api_key: str,
        timeout: int,
    ) -> None:
        """Store the shared session and connection settings."""
        self._session = session
        self._base_url = base_url.rstrip("/")
        self._api_key = api_key
        self._timeout = aiohttp.ClientTimeout(total=timeout)

    @property
    def _headers(self) -> dict[str, str]:
        """Return auth headers, omitting the Bearer token when no key is set."""
        if self._api_key:
            return {"Authorization": f"Bearer {self._api_key}"}
        return {}

    async def async_check_connection(self) -> None:
        """Best-effort reachability/auth check via GET /models.

        Raises AuroraWhisperAuthError on 401/403 and AuroraWhisperError on a
        connection failure. A missing /models endpoint (404/405/501) is
        tolerated as "reachable" — not every OpenAI-compatible server exposes
        it. Note: a server may also answer 200 without validating the key, so
        a clean check does not guarantee the key is correct.
        """
        url = f"{self._base_url}{ENDPOINT_MODELS}"
        try:
            async with self._session.get(
                url, headers=self._headers, timeout=self._timeout
            ) as resp:
                if resp.status in (401, 403):
                    raise AuroraWhisperAuthError(
                        f"Authentication rejected by the API (HTTP {resp.status})"
                    )
                if resp.status in (404, 405, 501):
                    # Endpoint not implemented but the host answered — treat as OK.
                    return
                if resp.status >= 400:
                    raise AuroraWhisperError(
                        f"Unexpected response from /models (HTTP {resp.status})"
                    )
        except aiohttp.ClientError as err:
            raise AuroraWhisperError(f"Could not connect to the API: {err}") from err
        except TimeoutError as err:
            raise AuroraWhisperError("Timed out connecting to the API") from err

    async def async_transcribe(
        self,
        wav_bytes: bytes,
        model: str,
        language: str | None = None,
        prompt: str | None = None,
    ) -> str:
        """Transcribe a WAV payload and return the recognised text.

        Sends multipart/form-data exactly like the OpenAI audio transcription
        API expects. Raises AuroraWhisperAuthError on 401/403 and AuroraWhisperError
        on any other failure.
        """
        url = f"{self._base_url}{ENDPOINT_TRANSCRIPTIONS}"

        form = aiohttp.FormData()
        form.add_field(
            "file", wav_bytes, filename="audio.wav", content_type="audio/wav"
        )
        form.add_field("model", model)
        if language:
            form.add_field("language", language)
        if prompt:
            form.add_field("prompt", prompt)
        form.add_field("response_format", "json")

        try:
            async with self._session.post(
                url, data=form, headers=self._headers, timeout=self._timeout
            ) as resp:
                if resp.status in (401, 403):
                    raise AuroraWhisperAuthError(
                        f"Authentication rejected by the API (HTTP {resp.status})"
                    )
                if resp.status >= 400:
                    body = (await resp.text())[:200]
                    raise AuroraWhisperError(
                        f"Transcription failed (HTTP {resp.status}): {body}"
                    )
                # response_format=json -> {"text": "..."}; tolerate lenient
                # content-type headers from non-OpenAI servers.
                data = await resp.json(content_type=None)
        except aiohttp.ClientError as err:
            raise AuroraWhisperError(f"Could not reach the API: {err}") from err
        except TimeoutError as err:
            raise AuroraWhisperError("Timed out waiting for transcription") from err

        text = data.get("text") if isinstance(data, dict) else None
        if text is None:
            raise AuroraWhisperError("API response did not contain a 'text' field")
        return text.strip()
