"""Audio helpers for the Aurora Whisper integration.

Deliberately free of any Home Assistant imports so the PCM->WAV wrapping can be
unit-tested standalone. The Assist pipeline delivers raw PCM (16-bit signed
little-endian, 16 kHz, mono); OpenAI-compatible transcription endpoints expect a
container, so we wrap it in a minimal in-memory WAV.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

import io
import wave

# Characteristics of the raw PCM the Assist pipeline produces.
AUDIO_SAMPLE_RATE = 16000
AUDIO_CHANNELS = 1
AUDIO_SAMPLE_WIDTH = 2  # bytes per sample (16-bit)


def pcm_to_wav(pcm: bytes) -> bytes:
    """Wrap raw 16-bit/16 kHz/mono PCM in a WAV container, in memory."""
    buffer = io.BytesIO()
    with wave.open(buffer, "wb") as wav_file:
        wav_file.setnchannels(AUDIO_CHANNELS)
        wav_file.setsampwidth(AUDIO_SAMPLE_WIDTH)
        wav_file.setframerate(AUDIO_SAMPLE_RATE)
        wav_file.writeframes(pcm)
    return buffer.getvalue()
