"""Config and options flow for the Aurora Whisper integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

import logging
from typing import Any

import voluptuous as vol

from homeassistant.config_entries import (
    ConfigFlow,
    ConfigFlowResult,
    OptionsFlow,
)
from homeassistant.core import callback
from homeassistant.helpers.aiohttp_client import async_get_clientsession
from homeassistant.helpers.selector import (
    NumberSelector,
    NumberSelectorConfig,
    NumberSelectorMode,
    TextSelector,
    TextSelectorConfig,
    TextSelectorType,
)

from . import AuroraWhisperConfigEntry
from .api import AuroraWhisperAuthError, AuroraWhisperClient, AuroraWhisperError
from .const import (
    CONF_API_KEY,
    CONF_BASE_URL,
    CONF_LANGUAGE,
    CONF_MODEL,
    CONF_PROMPT,
    CONF_TIMEOUT,
    DEFAULT_BASE_URL,
    DEFAULT_LANGUAGE,
    DEFAULT_MODEL,
    DEFAULT_PROMPT,
    DEFAULT_TIMEOUT,
    DOMAIN,
)

_LOGGER = logging.getLogger(__name__)


async def _validate_connection(hass, user_input: dict[str, Any]) -> None:
    """Best-effort connectivity/auth check; raises AuroraWhisperError on failure."""
    session = async_get_clientsession(hass)
    client = AuroraWhisperClient(
        session=session,
        base_url=user_input[CONF_BASE_URL],
        api_key=user_input.get(CONF_API_KEY, ""),
        timeout=user_input.get(CONF_TIMEOUT, DEFAULT_TIMEOUT),
    )
    await client.async_check_connection()


class AuroraWhisperConfigFlow(ConfigFlow, domain=DOMAIN):
    """Handle the initial configuration flow."""

    VERSION = 1

    async def async_step_user(
        self, user_input: dict[str, Any] | None = None
    ) -> ConfigFlowResult:
        """Collect connection settings and create the entry."""
        errors: dict[str, str] = {}

        if user_input is not None:
            try:
                await _validate_connection(self.hass, user_input)
            except AuroraWhisperAuthError:
                errors["base"] = "invalid_auth"
            except AuroraWhisperError:
                errors["base"] = "cannot_connect"
            else:
                model = user_input[CONF_MODEL]
                return self.async_create_entry(
                    title=f"Aurora Whisper ({model})",
                    data=user_input,
                )

        return self.async_show_form(
            step_id="user",
            data_schema=self._user_schema(user_input),
            errors=errors,
        )

    @staticmethod
    def _user_schema(user_input: dict[str, Any] | None) -> vol.Schema:
        """Build the setup schema, keeping any values the user already typed."""
        data = user_input or {}
        return vol.Schema(
            {
                vol.Required(
                    CONF_BASE_URL,
                    default=data.get(CONF_BASE_URL, DEFAULT_BASE_URL),
                ): TextSelector(TextSelectorConfig(type=TextSelectorType.URL)),
                vol.Optional(
                    CONF_API_KEY,
                    default=data.get(CONF_API_KEY, ""),
                ): TextSelector(TextSelectorConfig(type=TextSelectorType.PASSWORD)),
                vol.Required(
                    CONF_MODEL,
                    default=data.get(CONF_MODEL, DEFAULT_MODEL),
                ): TextSelector(),
                vol.Required(
                    CONF_LANGUAGE,
                    default=data.get(CONF_LANGUAGE, DEFAULT_LANGUAGE),
                ): TextSelector(),
                vol.Required(
                    CONF_TIMEOUT,
                    default=data.get(CONF_TIMEOUT, DEFAULT_TIMEOUT),
                ): NumberSelector(
                    NumberSelectorConfig(
                        min=5, max=300, step=1, mode=NumberSelectorMode.BOX
                    )
                ),
            }
        )

    @staticmethod
    @callback
    def async_get_options_flow(
        config_entry: AuroraWhisperConfigEntry,
    ) -> AuroraWhisperOptionsFlow:
        """Return the options flow handler."""
        return AuroraWhisperOptionsFlow()


class AuroraWhisperOptionsFlow(OptionsFlow):
    """Allow changing model / language / prompt without re-adding the entry."""

    async def async_step_init(
        self, user_input: dict[str, Any] | None = None
    ) -> ConfigFlowResult:
        """Manage the integration options."""
        if user_input is not None:
            return self.async_create_entry(data=user_input)

        current = {**self.config_entry.data, **self.config_entry.options}
        schema = vol.Schema(
            {
                vol.Required(
                    CONF_MODEL,
                    default=current.get(CONF_MODEL, DEFAULT_MODEL),
                ): TextSelector(),
                vol.Required(
                    CONF_LANGUAGE,
                    default=current.get(CONF_LANGUAGE, DEFAULT_LANGUAGE),
                ): TextSelector(),
                vol.Optional(
                    CONF_PROMPT,
                    default=current.get(CONF_PROMPT, DEFAULT_PROMPT),
                ): TextSelector(TextSelectorConfig(multiline=True)),
            }
        )
        return self.async_show_form(step_id="init", data_schema=schema)
