"""Constants for the aurora_whisper integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from typing import Final

from homeassistant.const import Platform

DOMAIN: Final = "aurora_whisper"
PLATFORMS: Final = [Platform.STT]

# --- Config entry data (set in the Config Flow) ---
CONF_BASE_URL: Final = "base_url"
CONF_API_KEY: Final = "api_key"
CONF_MODEL: Final = "model"
CONF_LANGUAGE: Final = "language"
CONF_TIMEOUT: Final = "timeout"

# --- Options (changed in the Options Flow) ---
CONF_PROMPT: Final = "prompt"

# --- Default values ---
DEFAULT_BASE_URL: Final = "https://api.staik.se/v1"
DEFAULT_MODEL: Final = "kb-whisper-large"
DEFAULT_LANGUAGE: Final = "sv"
DEFAULT_TIMEOUT: Final = 30
DEFAULT_PROMPT: Final = ""

# Languages advertised to the Assist pipeline. The configured default language
# is always ensured to be present at runtime even if it is not in this list.
# whisper-1 / KB-Whisper are multilingual; this is a curated, common subset.
SUPPORTED_LANGUAGES: Final = ["sv", "en", "no", "da", "fi", "de", "fr", "es"]

# Audio characteristics (raw PCM, 16-bit LE, 16 kHz, mono) live in audio.py,
# which is kept free of Home Assistant imports so the WAV wrapping is testable
# standalone.

# OpenAI-compatible REST endpoints (appended to the configured base_url).
ENDPOINT_TRANSCRIPTIONS: Final = "/audio/transcriptions"
ENDPOINT_MODELS: Final = "/models"
