"""Speech-to-Text platform for the Aurora Whisper integration.

Buffers the raw PCM stream the Assist pipeline delivers (16-bit LE, 16 kHz,
mono), wraps it in an in-memory WAV container and forwards it to the
OpenAI-compatible transcription endpoint via the async client.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from collections.abc import AsyncIterable
import logging

from homeassistant.components.stt import (
    AudioBitRates,
    AudioChannels,
    AudioCodecs,
    AudioFormats,
    AudioSampleRates,
    SpeechMetadata,
    SpeechResult,
    SpeechResultState,
    SpeechToTextEntity,
)
from homeassistant.core import HomeAssistant
from homeassistant.helpers.device_registry import DeviceInfo
from homeassistant.helpers.entity_platform import AddConfigEntryEntitiesCallback

from . import AuroraWhisperConfigEntry
from .api import AuroraWhisperError
from .audio import pcm_to_wav
from .const import (
    CONF_LANGUAGE,
    CONF_MODEL,
    CONF_PROMPT,
    DEFAULT_LANGUAGE,
    DEFAULT_MODEL,
    DEFAULT_PROMPT,
    DOMAIN,
    SUPPORTED_LANGUAGES,
)

_LOGGER = logging.getLogger(__name__)


async def async_setup_entry(
    hass: HomeAssistant,
    config_entry: AuroraWhisperConfigEntry,
    async_add_entities: AddConfigEntryEntitiesCallback,
) -> None:
    """Set up the Aurora Whisper entity from a config entry."""
    async_add_entities([AuroraWhisperSttEntity(config_entry)])


class AuroraWhisperSttEntity(SpeechToTextEntity):
    """STT entity that transcribes audio via an OpenAI-compatible Whisper API."""

    _attr_has_entity_name = True
    _attr_name = None

    def __init__(self, entry: AuroraWhisperConfigEntry) -> None:
        """Initialise the entity from its config entry."""
        self._entry = entry
        self._attr_unique_id = entry.entry_id
        self._attr_device_info = DeviceInfo(
            identifiers={(DOMAIN, entry.entry_id)},
            name=entry.title,
            manufacturer="Aurora Whisper",
            model=self._config.get(CONF_MODEL, DEFAULT_MODEL),
        )

    @property
    def _config(self) -> dict:
        """Return the merged config (data overlaid with options)."""
        return {**self._entry.data, **self._entry.options}

    @property
    def supported_languages(self) -> list[str]:
        """Return the languages advertised to the Assist pipeline."""
        configured = self._config.get(CONF_LANGUAGE, DEFAULT_LANGUAGE)
        languages = list(SUPPORTED_LANGUAGES)
        if configured and configured not in languages:
            languages.insert(0, configured)
        return languages

    @property
    def supported_formats(self) -> list[AudioFormats]:
        """Return the supported audio formats."""
        return [AudioFormats.WAV]

    @property
    def supported_codecs(self) -> list[AudioCodecs]:
        """Return the supported audio codecs."""
        return [AudioCodecs.PCM]

    @property
    def supported_bit_rates(self) -> list[AudioBitRates]:
        """Return the supported bit rates."""
        return [AudioBitRates.BITRATE_16]

    @property
    def supported_sample_rates(self) -> list[AudioSampleRates]:
        """Return the supported sample rates."""
        return [AudioSampleRates.SAMPLERATE_16000]

    @property
    def supported_channels(self) -> list[AudioChannels]:
        """Return the supported channel counts."""
        return [AudioChannels.CHANNEL_MONO]

    async def async_process_audio_stream(
        self, metadata: SpeechMetadata, stream: AsyncIterable[bytes]
    ) -> SpeechResult:
        """Buffer the PCM stream, transcribe it and return the result."""
        pcm = bytearray()
        async for chunk in stream:
            pcm.extend(chunk)

        if not pcm:
            _LOGGER.warning("Received an empty audio stream")
            return SpeechResult(None, SpeechResultState.ERROR)

        wav_bytes = pcm_to_wav(bytes(pcm))

        config = self._config
        model = config.get(CONF_MODEL, DEFAULT_MODEL)
        language = metadata.language or config.get(CONF_LANGUAGE, DEFAULT_LANGUAGE)
        prompt = config.get(CONF_PROMPT, DEFAULT_PROMPT)

        client = self._entry.runtime_data.client
        try:
            text = await client.async_transcribe(
                wav_bytes, model=model, language=language, prompt=prompt
            )
        except AuroraWhisperError as err:
            _LOGGER.error("Transcription failed: %s", err)
            return SpeechResult(None, SpeechResultState.ERROR)

        return SpeechResult(text, SpeechResultState.SUCCESS)
